### ISSUE TITLE
Unable to run when using NVIDIA GPU

### ISSUE THREAD

**Issue by sp4ghet** [fand/veda#106]
When I use an nvidia GPU with atom (GTX 1060M on Laptop, 1080 on Desktop) veda fails to initialize the WebGL context. It works when I set atom to use intel integrated graphics on laptop.

![image](https://user-images.githubusercontent.com/8775460/45301332-b645c300-b54b-11e8-9c2b-6166ab863116.png)

```
C:\Users\spaghet\.atom\packages\veda\node_modules\vedajs\node_modules\three\build\three.js:21332 THREE.WebGLRenderer: Error creating WebGL context.
WebGLRenderer @ C:\Users\spaghet\.atom\packages\veda\node_modules\vedajs\node_modules\three\build\three.js:21332
C:\Users\spaghet\.atom\packages\veda\node_modules\vedajs\node_modules\three\build\three.js:14891 Uncaught (in promise) TypeError: Cannot read property 'getExtension' of null
    at Object.get (C:\Users\spaghet\.atom\packages\veda\node_modules\vedajs\node_modules\three\build\three.js:14891:22)
    at initGLContext (C:\Users\spaghet\.atom\packages\veda\node_modules\vedajs\node_modules\three\build\three.js:21348:15)
    at new WebGLRenderer (C:\Users\spaghet\.atom\packages\veda\node_modules\vedajs\node_modules\three\build\three.js:21395:3)
    at new SoundRenderer (C:\Users\spaghet\.atom\packages\veda\node_modules\vedajs\lib\sound-renderer.js:88:25)
    at new Veda (C:\Users\spaghet\.atom\packages\veda\node_modules\vedajs\lib\veda.js:145:30)
    at new Player (C:\Users\spaghet\.atom\packages\veda\lib\player.js:62:21)
    at new App (C:\Users\spaghet\.atom\packages\veda\lib\app.js:73:23)
    at new Wrapper (C:\Users\spaghet\.atom\packages\veda\lib\wrapper.js:22:20)
    at Object._activate (C:\Users\spaghet\.atom\packages\veda\lib\index.js:83:19)
    at require.install.then (C:\Users\spaghet\.atom\packages\veda\lib\index.js:80:30)
    at <anonymous>
```

**Comment by sp4ghet** [comment]
https://discuss.atom.io/t/is-atom-able-to-use-the-gpu/46849/2

tried `--ignore-gpu-blacklist` with no luck...
This is probably an atom/electron problem but anyhoo...

**Comment by sp4ghet** [comment]
If you're using a laptop with nvidia optimus with windows, going to control panel and search for `nvidia control panel` 3D settings -> application settings -> `add` atom -> set `auto` to `integrated graphics` forces you to use integrated gpu (intel) which bypasses this error but still leaves you with an underutilized nvidia GPU

**Comment by sp4ghet** [comment]
` atom --ignore-gpu-blacklist=true --webgl=true --experimentalFeatures=true --experimentalCanvasFeatu
res=true`

none seem to solve the issue :/ 

https://github.com/electron/electron/issues/1277
https://github.com/electron/electron/issues/1319

**Comment by sp4ghet** [comment]
atom: 1.30.0
veda: 2.10.2
nvidia drivers: 399.24

**Comment by sp4ghet** [comment]
![image](https://user-images.githubusercontent.com/8775460/45305062-7b945880-b554-11e8-9c54-824ec415709a.png)

🤔
