### ISSUE TITLE
Failed to load the veda package

### ISSUE THREAD

**Issue by khoparzi** [fand/veda#113]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.2 x64
**Electron**: 2.0.9
**OS**: Mac OS X 10.13.6
**Thrown From**: [veda](https://github.com/fand/veda) package 2.10.2

### Stack Trace

Failed to load the veda package

```
At tok.exec is not a function

TypeError: tok.exec is not a function
    at /app.asar/node_modules/less/lib/less/parser/parser-input.js:113:21)
    at expect (/app.asar/node_modules/less/lib/less/parser/parser.js:58:82)
    at Object.definition (/app.asar/node_modules/less/lib/less/parser/parser.js:903:36)
    at Object.primary (/app.asar/node_modules/less/lib/less/parser/parser.js:263:34)
    at Object.parse (/app.asar/node_modules/less/lib/less/parser/parser.js:133:61)
    at loadFileCallback (/app.asar/node_modules/less/lib/less/import-manager.js:112:64)
    at /app.asar/node_modules/less/lib/less/import-manager.js:123:17
    at FileManager.loadFile (/app.asar/node_modules/less/lib/less-node/file-manager.js:33:9)
    at ImportManager.push (/app.asar/node_modules/less/lib/less/import-manager.js:118:35)
    at ImportVisitor.processImportNode (/app.asar/node_modules/less/lib/less/visitors/import-visitor.js:87:28)
    at ImportVisitor.visitImport (/app.asar/node_modules/less/lib/less/visitors/import-visitor.js:49:22)
    at Visitor.visit (/app.asar/node_modules/less/lib/less/visitors/visitor.js:74:32)
    at Visitor.visitArray (/app.asar/node_modules/less/lib/less/visitors/visitor.js:100:22)
    at Ruleset.accept (/app.asar/node_modules/less/lib/less/tree/ruleset.js:30:30)
    at Visitor.visit (/app.asar/node_modules/less/lib/less/visitors/visitor.js:81:18)
    at ImportVisitor.onImported (/app.asar/node_modules/less/lib/less/visitors/import-visitor.js:138:35)
    at ImportSequencer.tryRun (/app.asar/node_modules/less/lib/less/visitors/import-sequencer.js:37:37)
    at /app.asar/node_modules/less/lib/less/visitors/import-sequencer.js:19:25
    at fileParsedFunc (/app.asar/node_modules/less/lib/less/import-manager.js:50:17)
    at /app.asar/node_modules/less/lib/less/import-manager.js:113:21
    at finish (/app.asar/node_modules/less/lib/less/parser/parser.js:183:28)
    at Object.parse (/app.asar/node_modules/less/lib/less/parser/parser.js:191:24)
    at loadFileCallback (/app.asar/node_modules/less/lib/less/import-manager.js:112:64)
    at /app.asar/node_modules/less/lib/less/import-manager.js:123:17
    at FileManager.loadFile (/app.asar/node_modules/less/lib/less-node/file-manager.js:33:9)
    at ImportManager.push (/app.asar/node_modules/less/lib/less/import-manager.js:118:35)
    at ImportVisitor.processImportNode (/app.asar/node_modules/less/lib/less/visitors/import-visitor.js:87:28)
    at ImportVisitor.visitImport (/app.asar/node_modules/less/lib/less/visitors/import-visitor.js:49:22)
    at Visitor.visit (/app.asar/node_modules/less/lib/less/visitors/visitor.js:74:32)
    at Visitor.visitArray (/app.asar/node_modules/less/lib/less/visitors/visitor.js:100:22)
    at Ruleset.accept (/app.asar/node_modules/less/lib/less/tree/ruleset.js:30:30)
    at Visitor.visit (/app.asar/node_modules/less/lib/less/visitors/visitor.js:81:18)
    at ImportVisitor.run (/app.asar/node_modules/less/lib/less/visitors/import-visitor.js:22:27)
    at Object.parse (/app.asar/node_modules/less/lib/less/parser/parser.js:189:22)
    at Object.parse (/app.asar/node_modules/less/lib/less/parse.js:61:18)
    at Object.render (/app.asar/node_modules/less/lib/less/render.js:25:18)
```

### Commands

```
```

### Non-Core Packages

```
api-docs 0.0.6 
atom-beautify 0.33.4 
atom-browsersync 0.2.0 
atom-hydra 0.2.10 
autocomplete-glsl 0.2.3 
busy-signal 1.4.3 
compare-files 0.8.1 
corporate-gibberish 0.4.0 
CPP-Competitive-Programming-Snippets 1.0.1 
Extempore-Atom 0.4.2 
fountain 0.8.1 
foxdot 1.0.0 
gibber 0.1.3 
intentions 1.1.5 
language-glsl 2.0.4 
language-svg 0.9.2 
linter 2.2.0 
linter-fountain 0.2.0 
linter-glsl 2.1.4 
linter-ui-default 1.7.1 
OSCSourceCodeSenderView 0.0.1 
pdf-view 0.71.0 
processing 0.13.0 
processing-autocomplete 0.2.0 
processing-language 0.2.0 
script 3.18.1 
supercollider 0.9.1 
svg-preview 0.14.0 
teletype 0.13.3 
term 0.2.4 
tidal-autocode 0.6.4 
tidalcycles 0.12.1 
veda 2.10.2 
```

**Comment by fand** [comment]
Thx @khoparzi ,

The error message says Atom failed because its inner less package failed.
it seems not an issue of VEDA.

Maybe reinstalling Atom will solve the problem 😸
