### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getPath' of undefined

### ISSUE THREAD

**Issue by sp4ghet** [fand/veda#14]
This error gets thrown when you attempt to close out all tabs while in "watch active shader" mode and go to the blank window screen.

```
TypeError: Cannot read property 'getPath' of undefined
    at GlslLivecoder.loadShaderOfEditor (file:///C:/Users/rikuo/.atom/packages/glsl-livecoder/lib/glsl-livecoder.js:178:24)
    at GlslLivecoder.watchShader (file:///C:/Users/rikuo/.atom/packages/glsl-livecoder/lib/glsl-livecoder.js:137:10)
    at file:///C:/Users/rikuo/.atom/packages/glsl-livecoder/lib/glsl-livecoder.js:125:12
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\rikuo\AppData\Local\atom\app-1.19.5\resources\app\node_modules\event-kit\lib\emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (C:\Users\rikuo\AppData\Local\atom\app-1.19.5\resources\app\node_modules\event-kit\lib\emitter.js:141:34)
    at Workspace.didChangeActivePaneItemOnPaneContainer (C:\Users\rikuo\AppData\Local\atom\app-1.19.5\resources\app\src\workspace.js:502:30)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem (C:\Users\rikuo\AppData\Local\atom\app-1.19.5\resources\app\src\workspace-center.js:17:20)
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\rikuo\AppData\Local\atom\app-1.19.5\resources\app\node_modules\event-kit\lib\emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (C:\Users\rikuo\AppData\Local\atom\app-1.19.5\resources\app\node_modules\event-kit\lib\emitter.js:141:34)
    at PaneContainer.didChangeActiveItemOnPane (C:\Users\rikuo\AppData\Local\atom\app-1.19.5\resources\app\src\pane-container.js:284:26)
    at Pane.module.exports.Pane.setActiveItem (C:\Users\rikuo\AppData\Local\atom\app-1.19.5\resources\app\src\pane.js:339:22)
    at Pane.module.exports.Pane.removeItem (C:\Users\rikuo\AppData\Local\atom\app-1.19.5\resources\app\src\pane.js:626:22)
    at Pane.module.exports.Pane.destroyItem (C:\Users\rikuo\AppData\Local\atom\app-1.19.5\resources\app\src\pane.js:706:22)
    at Pane.module.exports.Pane.destroyActiveItem (C:\Users\rikuo\AppData\Local\atom\app-1.19.5\resources\app\src\pane.js:683:18)
    at Workspace.closeActivePaneItemOrEmptyPaneOrWindow (C:\Users\rikuo\AppData\Local\atom\app-1.19.5\resources\app\src\workspace.js:1703:48)
    at HTMLElement.core:close (C:\Users\rikuo\AppData\Local\atom\app-1.19.5\resources\app\src\register-default-commands.js:233:38)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\rikuo\AppData\Local\atom\app-1.19.5\resources\app\src\command-registry.js:265:35)
    at C:\Users\rikuo\AppData\Local\atom\app-1.19.5\resources\app\src\command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\rikuo\AppData\Local\atom\app-1.19.5\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\rikuo\AppData\Local\atom\app-1.19.5\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\rikuo\AppData\Local\atom\app-1.19.5\resources\app\src\window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (C:\Users\rikuo\AppData\Local\atom\app-1.19.5\resources\app\src\window-event-handler.js:3:65)
```

**Comment by fand** [comment]
Thanks ✨
