### ISSUE TITLE
Error while trying to update or install veda on atom

### ISSUE THREAD

**Issue by FernandoABava** [fand/veda#244]
Hi,
I've been using veda for a while, with no problems, untill a few days ago when I tried to use the camera example and it didn't load, it just showed a dark screen. I tried to update asuming that would help and it throw me an error every time, so I decided to better uninstall it and install it again from the settings menu of atom. No I don't have veda anymore and I can't install it. Every time I trie I get the same error,
````
> ffmpeg-static@4.2.6 install C:\Users\FERNAN~1.BAV\AppData\Local\Temp\apm-install-dir-2020628-11288-17qbkzw.gcuw\node_modules\veda\node_modules\ffmpeg-static
> node install.js


> glslang-validator-prebuilt@0.0.6 postinstall C:\Users\FERNAN~1.BAV\AppData\Local\Temp\apm-install-dir-2020628-11288-17qbkzw.gcuw\node_modules\veda\node_modules\glslang-validator-prebuilt
> node build.js

glslang-validator-prebuilt: Installing glslangValidator...

Error creating cache: ENOENT: no such file or directory, mkdir 'C:\Users\Fernando A. Bava\AppData\Local\ffmpeg-static-nodejs\Cache'

Error creating cache: ENOENT: no such file or directory, mkdir 'C:\Users\Fernando A. Bava\AppData\Local\ffmpeg-static-nodejs\Cache'
Error creating cache: ENOENT: no such file or directory, mkdir 'C:\Users\Fernando A. Bava\AppData\Local\ffmpeg-static-nodejs\Cache'
{ HTTPError: Response code 404 (Not Found)
    at EventEmitter.ee.on.res (C:\Users\FERNAN~1.BAV\AppData\Local\Temp\apm-install-dir-2020628-11288-17qbkzw.gcuw\node_modules\veda\node_modules\got\index.js:482:24)
    at EventEmitter.emit (events.js:198:13)
    at getResponse (C:\Users\FERNAN~1.BAV\AppData\Local\Temp\apm-install-dir-2020628-11288-17qbkzw.gcuw\node_modules\veda\node_modules\got\index.js:320:5)
    at Immediate.setImmediate (C:\Users\FERNAN~1.BAV\AppData\Local\Temp\apm-install-dir-2020628-11288-17qbkzw.gcuw\node_modules\veda\node_modules\got\index.js:147:6)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
  name: 'HTTPError',
  host: 'github.com',
  hostname: 'github.com',
  method: 'GET',
  path:
   '/KhronosGroup/glslang/releases/download/master-tot/glslang-master-windows-x64-Release.zip',
  protocol: 'https:',
  url:
   'https://github.com/KhronosGroup/glslang/releases/download/master-tot/glslang-master-windows-x64-Release.zip',
  statusCode: 404,
  statusMessage: 'Not Found',
  headers:
   { date: 'Tue, 28 Jul 2020 04:01:56 GMT',
     'content-type': 'text/plain; charset=utf-8',
     server: 'GitHub.com',
     status: '404 Not Found',
     vary: 'X-PJAX, Accept-Encoding, Accept, X-Requested-With',
     'cache-control': 'no-cache',
     'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
     'x-frame-options': 'deny',
     'x-content-type-options': 'nosniff',
     'x-xss-protection': '1; mode=block',
     'expect-ct':
      'max-age=2592000, report-uri="https://api.github.com/_private/browser/errors"',
     'content-security-policy':
      'default-src \'none\'; base-uri \'self\'; connect-src \'self\'; form-action \'self\'; img-src \'self\' data:; script-src \'self\'; style-src \'unsafe-inline\'',
     'content-encoding': 'gzip',
     'set-cookie':
      [ '_gh_sess=Fw2UJKyP8UOh%2Bni2W5Ip7xoBu6KR8XxmrI9A%2BhNW%2FpIqikPfgBtoWp9qr8BiF9OIqyM9tqIJK9E%2BrXDNO8fYqxtFysI4KhFJC68j0oiP8%2B51fcmUX%2FHTZqeoI18%2BZs8JMFK3PertsCNCOnklQVbbwcvGQewVKGwi69lcUG0Cvw0rr1afNZo0%2F%2FsTYNgdRXyq17KHBZxaqMS8D%2BX23yjKJ0hQzvIY2GJQg75t3Kr7bjbAxjI1DgAsbu7vYbowcOCVFoCzIT3ueIiilheYnJRCtA%3D%3D--9vXl78lLVpTMwdXF--IDyO13LUy1P8H0iaw1AeTw%3D%3D; Path=/; HttpOnly; Secure; SameSite=Lax',
        '_octo=GH1.1.733753984.1595908916; Path=/; Domain=github.com; Expires=Wed, 28 Jul 2021 04:01:56 GMT; Secure; SameSite=Lax',
        'logged_in=no; Path=/; Domain=github.com; Expires=Wed, 28 Jul 2021 04:01:56 GMT; HttpOnly; Secure; SameSite=Lax' ],
     'content-length': '40',
     connection: 'close',
     'x-github-request-id': '735C:1E7D:14A1A6D:1A35DF4:5F1FA333' } }
Error: Failed to download the binary to: C:\Users\FERNAN~1.BAV\AppData\Local\Temp\glslang-validator-prebuilt
    at promise.catch.e (C:\Users\FERNAN~1.BAV\AppData\Local\Temp\apm-install-dir-2020628-11288-17qbkzw.gcuw\node_modules\veda\node_modules\glslang-validator-prebuilt\build.js:47:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
glslang-validator-prebuilt Failed to install glslang-validator.
glslang-validator-prebuilt: Install failed.
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\FERNAN~1.BAV\AppData\Local\Temp\apm-install-dir-2020628-11288-17qbkzw.gcuw\package.json'
npm WARN apm-install-dir-2020628-11288-17qbkzw.gcuw No description
npm WARN apm-install-dir-2020628-11288-17qbkzw.gcuw No repository field.
npm WARN apm-install-dir-2020628-11288-17qbkzw.gcuw No README data
npm WARN apm-install-dir-2020628-11288-17qbkzw.gcuw No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! glslang-validator-prebuilt@0.0.6 postinstall: `node build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the glslang-validator-prebuilt@0.0.6 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Fernando A. Bava\.atom\.apm\_logs\2020-07-28T04_01_59_541Z-debug.log
````

Hope you can help me solve this, thanks :)

**Comment by FernandoABava** [comment]
Worked well after reseting my pc
